---
title: "Deep Knowledge Tutor"
author: "Larry Liu"
date: "February 5, 2016"
output: html_document
---

Notes:

---


```{r, echo=FALSE}
library('ggplot2')
library('animation')

#Change working directory
setwd("C:/Users/Larry/Dropbox/Stanford University/2015-2016/Winter Quarter/CS191W/deepcode")

```
```{r}
#Import count data
astCounts <- as.data.frame(read.table("C:/Users/Larry/Dropbox/Stanford University/2015-2016/Winter Quarter/CS191W/hoc1-9_new/hoc2/asts/counts.txt", sep="\t", header=FALSE))
colnames(astCounts) = c('astID', 'count')

#Import score data
astScores <- as.data.frame(read.table("C:/Users/Larry/Dropbox/Stanford University/2015-2016/Winter Quarter/CS191W/hoc1-9_new/hoc2/asts/unitTestResults.txt", sep="\t", header=FALSE))
colnames(astScores) = c('astID', 'score')

#Determine correctness of scores
astScores['correct'] = ifelse(astScores['score'] == 100 | astScores['score'] == 20, 1, 0)

astHist = ggplot(data=astCounts, aes(x=astID, y=count)) + geom_bar(stat='identity') + labs(title="AST frequency", x="AST ID", y="Frequency") + scale_y_log10() + scale_x_continuous()
astHist

astHist2 = ggplot(data=astCounts[astCounts$count > 1,], aes(x=astID, y=count)) + geom_bar(stat='identity') + labs(title="AST frequency", x="AST ID", y="Frequency") + scale_y_log10() + scale_x_continuous()
astHist2


astScorePlot = ggplot(data=astScores, aes(x=astID, y=score, colour=as.factor(correct))) + geom_point() + labs(title="AST Scores", x="AST ID", y="Score") + scale_y_continuous(breaks=seq(0,100,10), limits=c(0,100)) + scale_x_continuous() + scale_color_manual(values=c("red", "green"))
astScorePlot

```
```{r}
trajCounts <- as.data.frame(read.table("C:/Users/Larry/Dropbox/Stanford University/2015-2016/Winter Quarter/CS191W/hoc1-9_new/hoc2/trajectories/counts.txt", sep="\t", header=FALSE))
colnames(trajCounts) = c('trajID', 'count')

trajHist = ggplot(data=trajCounts, aes(x=trajID, y=count)) + geom_bar(stat='identity') + labs(title="Trajectory frequency", x="Trajectory ID", y="Frequency") + scale_y_log10() + scale_x_continuous()
trajHist

#Remove all trajectory IDs with count 1
trajHist2 = ggplot(data=trajCounts[trajCounts$count > 1,], aes(x=trajID, y=count)) + geom_bar(stat='identity') + labs(title="Trajectory frequency", x="Trajectory ID", y="Frequency") + scale_y_log10() + scale_x_continuous()
trajHist2 

```
